
spring:
     application:
          name: spirng-boot-rabbitmq
     rabbitmq:
          host: 192.168.1.106
          port: 5672
          username: hbsit
          password: hbsit
          virtual-host: /
          exchange: EXCHANGE_DIRECT_TEST 
          queue: QUEUE_TEST
